# 1.VACCUME CLEANER WITH ARRAY REPRESENTATION

In [ ]:
import numpy as np
import random
def gen_grid(n):
    return np.random.randint(0, 2, (n, n))
def display(grid):
    print(grid)
    print()
def clean_grid(grid):
    vacuum = [0, 0]  
    print("Initial grid:")
    display(grid)
    for i in range(n):
        for j in range(n):
            vacuum = [i, j]
            print(f"Moving the vacuum to position ({i+1}, {j+1})")
            print(f"cleaning tile: ({i+1}, {j+1})")
            if grid[i, j] == 1:
                grid[i, j] = 0
            display(grid)
    print("Final grid:")
    display(grid)
n = int(input("Enter the size of n: "))
grid = gen_grid(n)
clean_grid(grid)

Initial grid:
[[1 1 0 0]
 [0 0 1 1]
 [1 0 0 1]
 [0 0 1 0]]

Moving the vacuum to position (1, 1)
cleaning tile: (1, 1)
[[0 1 0 0]
 [0 0 1 1]
 [1 0 0 1]
 [0 0 1 0]]

Moving the vacuum to position (1, 2)
cleaning tile: (1, 2)
[[0 0 0 0]
 [0 0 1 1]
 [1 0 0 1]
 [0 0 1 0]]

Moving the vacuum to position (1, 3)
cleaning tile: (1, 3)
[[0 0 0 0]
 [0 0 1 1]
 [1 0 0 1]
 [0 0 1 0]]

Moving the vacuum to position (1, 4)
cleaning tile: (1, 4)
[[0 0 0 0]
 [0 0 1 1]
 [1 0 0 1]
 [0 0 1 0]]

Moving the vacuum to position (2, 1)
cleaning tile: (2, 1)
[[0 0 0 0]
 [0 0 1 1]
 [1 0 0 1]
 [0 0 1 0]]

Moving the vacuum to position (2, 2)
cleaning tile: (2, 2)
[[0 0 0 0]
 [0 0 1 1]
 [1 0 0 1]
 [0 0 1 0]]

Moving the vacuum to position (2, 3)
cleaning tile: (2, 3)
[[0 0 0 0]
 [0 0 0 1]
 [1 0 0 1]
 [0 0 1 0]]

Moving the vacuum to position (2, 4)
cleaning tile: (2, 4)
[[0 0 0 0]
 [0 0 0 0]
 [1 0 0 1]
 [0 0 1 0]]

Moving the vacuum to position (3, 1)
cleaning tile: (3, 1)
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 1]
 [0 0 1 

In [34]:
import random
random.randint(0,100)
print(np.random.randint(0,100,(3,2)))

[[68 31]
 [69 59]
 [64 46]]


In [9]:

def display1(a):
    for i in a:
        print(i)

a=[[0, 0, 0], [0, 1, 0], [0, 1, 1]]
display1(a)

[0, 0, 0]
[0, 1, 0]
[0, 1, 1]


In [10]:
a=[[10,20,30],[40,50,60]]
for i in range(len(a)):
    for j in range(len(a[i])):
        print(a[i][j])

10
20
30
40
50
60


# 2. VACCUME CLEANER WITH MATRIX REPRESENTATION

In [41]:
import random
def gen_grid(n):
    return [[random.randint(0,1) for i in range(n)] for i in range(n)]
def display(a):
    for i in a:
        print(i)
    print()
def clean_grid(grid):
    n=len(grid)
    vaccume=[0,0]#list
    print("initial grid=")
    display(grid)
    for i in range(n):
        for j in range(n):
            vaccume=[i,j]
            print("moving the vaccume position to (%d,%d)"%(i,j))
            if(grid[i][j]==1):
                grid[i][j]=0
            display(grid)
    print("final grid")
    display(grid)
number=int(input("enter the size of n="))
grid=gen_grid(number)
clean_grid(grid)

initial grid=
[1, 1, 0, 1]
[0, 0, 1, 1]
[0, 1, 0, 0]
[1, 1, 0, 0]

moving the vaccume position to (0,0)
[0, 1, 0, 1]
[0, 0, 1, 1]
[0, 1, 0, 0]
[1, 1, 0, 0]

moving the vaccume position to (0,1)
[0, 0, 0, 1]
[0, 0, 1, 1]
[0, 1, 0, 0]
[1, 1, 0, 0]

moving the vaccume position to (0,2)
[0, 0, 0, 1]
[0, 0, 1, 1]
[0, 1, 0, 0]
[1, 1, 0, 0]

moving the vaccume position to (0,3)
[0, 0, 0, 0]
[0, 0, 1, 1]
[0, 1, 0, 0]
[1, 1, 0, 0]

moving the vaccume position to (1,0)
[0, 0, 0, 0]
[0, 0, 1, 1]
[0, 1, 0, 0]
[1, 1, 0, 0]

moving the vaccume position to (1,1)
[0, 0, 0, 0]
[0, 0, 1, 1]
[0, 1, 0, 0]
[1, 1, 0, 0]

moving the vaccume position to (1,2)
[0, 0, 0, 0]
[0, 0, 0, 1]
[0, 1, 0, 0]
[1, 1, 0, 0]

moving the vaccume position to (1,3)
[0, 0, 0, 0]
[0, 0, 0, 0]
[0, 1, 0, 0]
[1, 1, 0, 0]

moving the vaccume position to (2,0)
[0, 0, 0, 0]
[0, 0, 0, 0]
[0, 1, 0, 0]
[1, 1, 0, 0]

moving the vaccume position to (2,1)
[0, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[1, 1, 0, 0]

moving the vaccume position to (2

# 3.TWO VACCUME CLEANER IN OPPOSITE DIRECTION AND THEY ARE MOVING IN A RANDOM POSITION

In [39]:
import numpy as np
import random
def gen_grid(n):
    return np.random.randint(0, 2, (n, n))
def display(grid):
    print(grid)
    print()
def move_randomly(grid, vacuum_position):
    n = len(grid)
    vacuum_position[0] = random.randint(0, n - 1)  
    vacuum_position[1] = random.randint(0, n - 1)  
    return vacuum_position
def clean_grid(grid):
    n = len(grid)
    vacuum1 = [0, 0]
    vacuum2 = [n - 1, n - 1]
    print("Initial grid:")
    display(grid)
    while np.any(grid == 1): 
        vacuum1 = move_randomly(grid, vacuum1)
        print(f"Vacuum 1 moved to position {vacuum1}")
        if grid[vacuum1[0], vacuum1[1]] == 1:  
            grid[vacuum1[0], vacuum1[1]] = 0 
            print(f"Vacuum 1 cleaned position {vacuum1}")
        else:
            print("Tile is already cleaned")
        vacuum2 = move_randomly(grid, vacuum2)
        print(f"Vacuum 2 moved to position {vacuum2}")
        if grid[vacuum2[0], vacuum2[1]] == 1: 
            grid[vacuum2[0], vacuum2[1]] = 0  
            print(f"Vacuum 2 cleaned position {vacuum2}")
        else:
            print("Tile is already cleaned")
        display(grid)  
    print("Final grid:")
    display(grid)
number = int(input("Enter the size of the grid (n): "))
grid = gen_grid(number)
clean_grid(grid)

Initial grid:
[[0 1 0 0]
 [1 1 0 1]
 [0 1 0 0]
 [1 1 0 1]]

Vacuum 1 moved to position [2, 1]
Vacuum 1 cleaned position [2, 1]
Vacuum 2 moved to position [2, 1]
Tile is already cleaned
[[0 1 0 0]
 [1 1 0 1]
 [0 0 0 0]
 [1 1 0 1]]

Vacuum 1 moved to position [2, 1]
Tile is already cleaned
Vacuum 2 moved to position [3, 1]
Vacuum 2 cleaned position [3, 1]
[[0 1 0 0]
 [1 1 0 1]
 [0 0 0 0]
 [1 0 0 1]]

Vacuum 1 moved to position [3, 1]
Tile is already cleaned
Vacuum 2 moved to position [3, 2]
Tile is already cleaned
[[0 1 0 0]
 [1 1 0 1]
 [0 0 0 0]
 [1 0 0 1]]

Vacuum 1 moved to position [1, 3]
Vacuum 1 cleaned position [1, 3]
Vacuum 2 moved to position [2, 3]
Tile is already cleaned
[[0 1 0 0]
 [1 1 0 0]
 [0 0 0 0]
 [1 0 0 1]]

Vacuum 1 moved to position [0, 2]
Tile is already cleaned
Vacuum 2 moved to position [2, 3]
Tile is already cleaned
[[0 1 0 0]
 [1 1 0 0]
 [0 0 0 0]
 [1 0 0 1]]

Vacuum 1 moved to position [1, 1]
Vacuum 1 cleaned position [1, 1]
Vacuum 2 moved to position [2, 0]
Ti

# 8 PUZZLE PROBLEM

In [49]:
from collections import deque
class EightPuzzle:
    def __init__(self, initial_state, goal_state):
        self.initial_state = initial_state
        self.goal_state = goal_state
    def find_blank(self, state):
        for i, row in enumerate(state):
            if 0 in row:
                return i, row.index(0)
    def is_goal_state(self, state):
        return state == self.goal_state
    def get_neighbors(self, state):
        neighbors = []
        blank_row, blank_col = self.find_blank(state)
        moves = [(-1, 0), (1, 0), (0, -1), (0, 1)]  # Up, Down, Left, Right
        for dr, dc in moves:
            new_row, new_col = blank_row + dr, blank_col + dc
            if 0 <= new_row < 3 and 0 <= new_col < 3:
                new_state = [row[:] for row in state]
                new_state[blank_row][blank_col], new_state[new_row][new_col] = (
                    new_state[new_row][new_col],
                    new_state[blank_row][blank_col],
                )
                neighbors.append(new_state)
        return neighbors
    def solve(self):
        queue = deque([(self.initial_state, [])])
        visited = set()
        while queue:
            current_state, path = queue.popleft()
            state_tuple = tuple(tuple(row) for row in current_state)
            if state_tuple in visited:
                continue
            visited.add(state_tuple)
            if self.is_goal_state(current_state):
                return path
            for neighbor in self.get_neighbors(current_state):
                queue.append((neighbor, path + [neighbor]))
        return None
initial_state = [
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8]
]
goal_state = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 0]
]
puzzle = EightPuzzle(initial_state, goal_state)
solution = puzzle.solve()
if solution:
    print("Solution found:")
    for step in solution:
        for row in step:
            print(row)
        print()
else:
    print("No solution exists.")

Solution found:
[3, 1, 2]
[0, 4, 5]
[6, 7, 8]

[3, 1, 2]
[4, 0, 5]
[6, 7, 8]

[3, 1, 2]
[4, 5, 0]
[6, 7, 8]

[3, 1, 0]
[4, 5, 2]
[6, 7, 8]

[3, 0, 1]
[4, 5, 2]
[6, 7, 8]

[0, 3, 1]
[4, 5, 2]
[6, 7, 8]

[4, 3, 1]
[0, 5, 2]
[6, 7, 8]

[4, 3, 1]
[6, 5, 2]
[0, 7, 8]

[4, 3, 1]
[6, 5, 2]
[7, 0, 8]

[4, 3, 1]
[6, 0, 2]
[7, 5, 8]

[4, 0, 1]
[6, 3, 2]
[7, 5, 8]

[4, 1, 0]
[6, 3, 2]
[7, 5, 8]

[4, 1, 2]
[6, 3, 0]
[7, 5, 8]

[4, 1, 2]
[6, 0, 3]
[7, 5, 8]

[4, 1, 2]
[0, 6, 3]
[7, 5, 8]

[0, 1, 2]
[4, 6, 3]
[7, 5, 8]

[1, 0, 2]
[4, 6, 3]
[7, 5, 8]

[1, 2, 0]
[4, 6, 3]
[7, 5, 8]

[1, 2, 3]
[4, 6, 0]
[7, 5, 8]

[1, 2, 3]
[4, 0, 6]
[7, 5, 8]

[1, 2, 3]
[4, 5, 6]
[7, 0, 8]

[1, 2, 3]
[4, 5, 6]
[7, 8, 0]



# 7.WATER JUG PROBLEM

In [1]:
def pour_jug(jug1, jug2, capacity1, capacity2):
    steps = []  
    while True:
        steps.append((jug1, jug2))
        if jug1 == 2 or jug2 == 2:
            break
        if jug1 == 0:
            jug1 = capacity1
        elif jug2 < capacity2:
            transfer = min(jug1, capacity2 - jug2)
            jug1 -= transfer
            jug2 += transfer
        elif jug2 == capacity2:
            jug2 = 0
    return steps
def main():
    capacity1 = 4  
    capacity2 = 3
    jug1, jug2 = 0, 0
    steps = pour_jug(jug1, jug2, capacity1, capacity2)
    print("Steps to measure exactly 2 liters:")
    for step in steps:
        print(f"Jug1: {step[0]} liters, Jug2: {step[1]} liters")


main()

Steps to measure exactly 2 liters:
Jug1: 0 liters, Jug2: 0 liters
Jug1: 4 liters, Jug2: 0 liters
Jug1: 1 liters, Jug2: 3 liters
Jug1: 1 liters, Jug2: 0 liters
Jug1: 0 liters, Jug2: 1 liters
Jug1: 4 liters, Jug2: 1 liters
Jug1: 2 liters, Jug2: 3 liters


# 4.MONKEY BANANA PROBLEM USING ARRAYS

In [48]:
import numpy as np
import random
def create_scene(n):
    grid = np.full((n, n), ".")  
    positions = random.sample(range(n * n), 3)
    monkey_position = [positions[0] // n, positions[0] % n]
    chair_position = [positions[1] // n, positions[1] % n]
    banana_position = [positions[2] // n, positions[2] % n]
    grid[monkey_position[0], monkey_position[1]] = "M"
    grid[chair_position[0], chair_position[1]] = "C"
    grid[banana_position[0], banana_position[1]] = "B"
    return grid, monkey_position, chair_position, banana_position
def print_scene(grid):
    for row in grid:
        print(" ".join(row))
    print()
def move_monkey(grid, monkey_position, target_position):
    while monkey_position != target_position:
        prev_position = monkey_position[:]
        if monkey_position[0] < target_position[0]:
            monkey_position[0] += 1
        elif monkey_position[0] > target_position[0]:
            monkey_position[0] -= 1
        elif monkey_position[1] < target_position[1]:
            monkey_position[1] += 1
        elif monkey_position[1] > target_position[1]:
            monkey_position[1] -= 1
        update_grid(grid, monkey_position, "M")
        print(f"Monkey moved from {prev_position} to {monkey_position}")
        print_scene(grid)
    print("Monkey reached the chair.")
def move_chair(grid, chair_position, target_position):
    while chair_position != target_position:
        prev_position = chair_position[:]
        if chair_position[0] < target_position[0]:
            chair_position[0] += 1
        elif chair_position[0] > target_position[0]:
            chair_position[0] -= 1
        elif chair_position[1] < target_position[1]:
            chair_position[1] += 1
        elif chair_position[1] > target_position[1]:
            chair_position[1] -= 1
        update_grid(grid, chair_position, "C")
        print(f"Chair moved from {prev_position} to {chair_position}")
        print_scene(grid)
    print(f"Chair is placed below the banana at {target_position}.")
def update_grid(grid, position, symbol):
    grid[grid == symbol] = "."  
    grid[position[0], position[1]] = symbol  
def grab_banana():
    print("The monkey climbs the chair and grabs the banana!\n")
n = int(input("Enter the grid size (n x n): "))
grid, monkey_position, chair_position, banana_position = create_scene(n)
print("Initial Scene:")
print_scene(grid)
move_monkey(grid, monkey_position, chair_position)
move_chair(grid, chair_position, [banana_position[0] + 1, banana_position[1]])
move_monkey(grid, monkey_position, [banana_position[0] + 1, banana_position[1]])
grab_banana()


Initial Scene:
. . . .
B . . .
. . . .
. C . M

Monkey moved from [3, 3] to [3, 2]
. . . .
B . . .
. . . .
. C M .

Monkey moved from [3, 2] to [3, 1]
. . . .
B . . .
. . . .
. M . .

Monkey reached the chair.
Chair moved from [3, 1] to [2, 1]
. . . .
B . . .
. C . .
. M . .

Chair moved from [2, 1] to [2, 0]
. . . .
B . . .
C . . .
. M . .

Chair is placed below the banana at [2, 0].
Monkey moved from [3, 1] to [2, 1]
. . . .
B . . .
C M . .
. . . .

Monkey moved from [2, 1] to [2, 0]
. . . .
B . . .
M . . .
. . . .

Monkey reached the chair.
The monkey climbs the chair and grabs the banana!



# 5.MONKEY BANANA PROBLEM USING MATRIX

In [27]:
import random
def create_scene(n):
    grid = [["." for _ in range(n)] for _ in range(n)]
    positions = random.sample([(i, j) for i in range(n) for j in range(n)], 3)
    monkey_position = list(positions[0])
    chair_position = list(positions[1])
    banana_position = list(positions[2])
    grid[monkey_position[0]][monkey_position[1]] = "M"
    grid[chair_position[0]][chair_position[1]] = "C"
    grid[banana_position[0]][banana_position[1]] = "B"
    return grid, monkey_position, chair_position, banana_position
def print_scene(grid):
    for row in grid:
        print(" ".join(row))
    print()
def move_monkey(grid, monkey_position, target_position):
    while monkey_position != target_position:
        prev_position = monkey_position[:]
        if monkey_position[0] < target_position[0]:
            monkey_position[0] += 1
        elif monkey_position[0] > target_position[0]:
            monkey_position[0] -= 1
        elif monkey_position[1] < target_position[1]:
            monkey_position[1] += 1
        elif monkey_position[1] > target_position[1]:
            monkey_position[1] -= 1
        update_grid(grid, monkey_position, "M")
        print(f"Monkey moved from {prev_position} to {monkey_position}")
        print_scene(grid)
    print(f"Monkey reached the target position {target_position}.")
def move_chair(grid, chair_position, target_position):
    while chair_position != target_position:
        prev_position = chair_position[:]
        if chair_position[0] < target_position[0]:
            chair_position[0] += 1
        elif chair_position[0] > target_position[0]:
            chair_position[0] -= 1
        elif chair_position[1] < target_position[1]:
            chair_position[1] += 1
        elif chair_position[1] > target_position[1]:
            chair_position[1] -= 1
        update_grid(grid, chair_position, "C")
        print(f"Chair moved from {prev_position} to {chair_position}")
        print_scene(grid)
    print(f"Chair is placed below the banana at {target_position}.")
def update_grid(grid, position, symbol):
    for i in range(len(grid)):
        for j in range(len(grid[i])):
            if grid[i][j] == symbol:
                grid[i][j] = "."
    grid[position[0]][position[1]] = symbol
def grab_banana():
    print("The monkey climbs the chair and grabs the banana!\n")
if __name__ == "__main__":
    n = int(input("Enter the grid size (n x n): "))
    grid, monkey_position, chair_position, banana_position = create_scene(n)
    print("Initial Scene:")
    print_scene(grid)
    print("Step 1: Monkey moves to the chair.")
    move_monkey(grid, monkey_position, [chair_position[0], chair_position[1]])
    print("Step 2: Monkey pushes the chair below the banana.")
    move_chair(grid, chair_position, [banana_position[0] + 1, banana_position[1]])
    print("Step 3: Monkey moves to the chair placed below the banana.")
    move_monkey(grid, monkey_position, [banana_position[0] + 1, banana_position[1]])
    grab_banana()

Initial Scene:
M . .
. . B
. . C

Monkey moved:
. . .
M . B
. . C

Monkey moved:
. . .
. . B
M . C

Monkey moved:
. . .
. . B
. M C

Monkey moved:
. . .
. . B
. . M

The monkey climbs the chair and grabs the banana!



# 6


In [46]:
import random
def print_grid(grid):
    for row in grid:
        print(" | ".join(row))
    print("\n")
def generate_random_positions(grid_size, num_positions):
    positions = set()
    while len(positions) < num_positions:
        positions.add((random.randint(0, grid_size - 1), random.randint(0, grid_size - 1)))
    return list(positions)
def simulate_monkeys(grid, monkey1, monkey2, chair, banana):
    while True:
        print("Current Grid:")
        print_grid(grid)
        if monkey1 == chair:
            print("Monkey 1 reached the chair and grabbed the banana!")
            grid[banana[0]][banana[1]] = "grabbed"
            break
        elif monkey2 == chair:
            print("Monkey 2 reached the chair and grabbed the banana!")
            grid[banana[0]][banana[1]] = "grabbed"
            break
        if monkey1[0] < chair[0] and monkey1[1] < chair[1]:
            grid[monkey1[0]][monkey1[1]] = "__"
            monkey1 = (monkey1[0] + 1, monkey1[1] + 1)
        elif monkey1[0] < chair[0] and monkey1[1] > chair[1]:
            grid[monkey1[0]][monkey1[1]] = "__"
            monkey1 = (monkey1[0] + 1, monkey1[1] - 1)
        elif monkey1[0] > chair[0] and monkey1[1] < chair[1]:
            grid[monkey1[0]][monkey1[1]] = "__"
            monkey1 = (monkey1[0] - 1, monkey1[1] + 1)
        elif monkey1[0] > chair[0] and monkey1[1] > chair[1]:
            grid[monkey1[0]][monkey1[1]] = "__"
            monkey1 = (monkey1[0] - 1, monkey1[1] - 1)
        elif monkey1[0] < chair[0]:
            grid[monkey1[0]][monkey1[1]] = "__"
            monkey1 = (monkey1[0] + 1, monkey1[1])
        elif monkey1[0] > chair[0]:
            grid[monkey1[0]][monkey1[1]] = "__"
            monkey1 = (monkey1[0] - 1, monkey1[1])
        elif monkey1[1] < chair[1]:
            grid[monkey1[0]][monkey1[1]] = "__"
            monkey1 = (monkey1[0], monkey1[1] + 1)
        elif monkey1[1] > chair[1]:
            grid[monkey1[0]][monkey1[1]] = "__"
            monkey1 = (monkey1[0], monkey1[1] - 1)
        grid[monkey1[0]][monkey1[1]] = "M1"

        if monkey2[0] < chair[0] and monkey2[1] < chair[1]:
            grid[monkey2[0]][monkey2[1]] = "__"
            monkey2 = (monkey2[0] + 1, monkey2[1] + 1)
        elif monkey2[0] < chair[0] and monkey2[1] > chair[1]:
            grid[monkey2[0]][monkey2[1]] = "__"
            monkey2 = (monkey2[0] + 1, monkey2[1] - 1)
        elif monkey2[0] > chair[0] and monkey2[1] < chair[1]:
            grid[monkey2[0]][monkey2[1]] = "__"
            monkey2 = (monkey2[0] - 1, monkey2[1] + 1)
        elif monkey2[0] > chair[0] and monkey2[1] > chair[1]:
            grid[monkey2[0]][monkey2[1]] = "__"
            monkey2 = (monkey2[0] - 1, monkey2[1] - 1)
        elif monkey2[0] < chair[0]:
            grid[monkey2[0]][monkey2[1]] = "__"
            monkey2 = (monkey2[0] + 1, monkey2[1])
        elif monkey2[0] > chair[0]:
            grid[monkey2[0]][monkey2[1]] = "__"
            monkey2 = (monkey2[0] - 1, monkey2[1])
        elif monkey2[1] < chair[1]:
            grid[monkey2[0]][monkey2[1]] = "__"
            monkey2 = (monkey2[0], monkey2[1] + 1)
        elif monkey2[1] > chair[1]:
            grid[monkey2[0]][monkey2[1]] = "__"
            monkey2 = (monkey2[0], monkey2[1] - 1)
        grid[monkey2[0]][monkey2[1]] = "M2"
n = int(input("Enter the vlaue of n"))
grid = [["__" for _ in range(n)] for _ in range(n)]
positions = generate_random_positions(n, 4)
banana, chair, monkey1, monkey2 = positions
grid[banana[0]][banana[1]] = "Ba"
grid[chair[0]][chair[1]] = "Ch"
grid[monkey1[0]][monkey1[1]] = "M1"
grid[monkey2[0]][monkey2[1]] = "M2"
simulate_monkeys(grid, monkey1, monkey2, chair, banana)


Current Grid:
M2 | __ | __
__ | __ | __
Ba | M1 | Ch


Current Grid:
__ | __ | __
__ | M2 | __
Ba | __ | M1


Monkey 1 reached the chair and grabbed the banana!


In [38]:
def water_jug_problem(jug_x, jug_y, target):
    visited = set()
    steps = []
    def dfs(x, y):
        if (x, y) in visited or x > jug_x or y > jug_y or x < 0 or y < 0:
            return False
        visited.add((x, y))
        steps.append((x, y))
        if x == target or y == target:
            return True
        return (dfs(jug_x, y) or  # Fill Jug X
                dfs(x, jug_y) or  # Fill Jug Y
                dfs(0, y) or      # Empty Jug X
                dfs(x, 0) or      # Empty Jug Y
                dfs(x - min(x, jug_y - y), y + min(x, jug_y - y)) or  # Pour X -> Y
                dfs(x + min(y, jug_x - x), y - min(y, jug_x - x)))    # Pour Y -> X
    if dfs(0, 0):
        print("Solution found:", steps)
    else:
        print("No solution found.")
jug_x = int(input("Enter capacity of jug x"))  # Capacity of Jug X
jug_y = int(input("Enter capacity of jug y"))  # Capacity of Jug Y
target = int(input("Enter target"))  # Target volume
water_jug_problem(jug_x, jug_y, target)

Solution found: [(0, 0), (4, 0), (4, 3), (0, 3), (3, 0), (3, 3), (4, 2), (0, 2), (2, 0), (2, 3), (4, 1)]
